#!/bin/bash
dot -o classes.eps -Tps ../doc/classes.dot
dot -o switch.eps -Tps ../doc/switch.dot
dot -o if.eps -Tps ../doc/if.dot
dot -o for.eps -Tps ../doc/for.dot
dot -o for2.eps -Tps ../doc/for2.dot
dot -o forin.eps -Tps ../doc/forin.dot
dot -o do.eps -Tps ../doc/do.dot
dot -o try.eps -Tps ../doc/try.dot
dot -o with.eps -Tps ../doc/with.dot
dot -o function.eps -Tps ../doc/function.dot
dot -o flow.eps -Tps  ../doc/flow.dot
dot -o number.eps -Tps  ../doc/number.dot
dot -o errornext.eps -Tps  ../doc/errornext.dot
dot -o errorzero.eps -Tps  ../doc/errorzero.dot
dot -o dim.eps -Tps  ../doc/dim.dot
dot -o redim.eps -Tps  ../doc/redim.dot
dot -o erase.eps -Tps  ../doc/erase.dot
dot -o call.eps -Tps  ../doc/call.dot
dot -o callobj.eps -Tps  ../doc/callobj.dot
dot -o set.eps -Tps  ../doc/set.dot
dot -o randomize.eps -Tps  ../doc/randomize.dot
dot -o const.eps -Tps  ../doc/const.dot
dot -o sub.eps -Tps  ../doc/sub.dot
dot -o whend.eps -Tps  ../doc/whend.dot
dot -o vbfor.eps -Tps  ../doc/vbfor.dot
dot -o vbfor2.eps -Tps  ../doc/vbfor2.dot
dot -o vbforeach.eps -Tps  ../doc/vbforeach.dot
dot -o vbif.eps -Tps  ../doc/vbif.dot
dot -o vbselect.eps -Tps  ../doc/vbselect.dot
